server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    username: ${DBMS_PASSWORD:root}
    password: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt: 
  signerKey: "hsXvHmx4GkUzKUBZsnmBrTQTlyGSMWEmnOjoBXobf/nvflDpkFqQO1DJG4xmBCBt"